id: PB3CD6846
initial_creation_type: input
source_metadata:
  title: Garwang Chökyi Gyaltsen
  language: en
  description: 'Texts by and about the Fourth Shechen Rabjam, Garwang Chökyi Gyaltsen
    (gar dbang chos kyi rgyal mtshan, 1811?–1862):'
  volume:
    36b25032404b40f79866573c91e43ad3:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Prayers
created_at: '2022-02-28T23:21:46.856880'
last_modified_at: '2022-02-28T23:21:46.856886'
